name: user_repository
description: Dart package which manages the user domain.
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  http: ^0.13.1
  flutter_secure_storage: ^4.1.0
